### ISSUE TITLE
Error when installing with pip

### ISSUE THREAD

**Issue by inercia** [IljaOrlovs/vbox#1]
I get this error when installing with pip:

``` bash
pip install vbox
Downloading/unpacking vbox
  Downloading vbox-0.2.5.zip
  Running setup.py egg_info for package vbox
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/private/tmp/pip_build_root/vbox/setup.py", line 30, in <module>
        long_description=open("README.rst").read(),
    IOError: [Errno 2] No such file or directory: 'README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/private/tmp/pip_build_root/vbox/setup.py", line 30, in <module>

    long_description=open("README.rst").read(),

IOError: [Errno 2] No such file or directory: 'README.rst'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /private/tmp/pip_build_root/vbox
```

**Comment by iamsudip** [comment]
@inercia The pypi package lacks the README.rst file. So, it is happening. I think one MANIFEST.in file with all the file names to include with the package(while creating the package) will solve the problem.

**Comment by synthesizerpatel** [comment]
I ran into this same problem. Installing from git worked great, but being able to install from pip would be more great. Thanks for your module and your effort! Big respect!

**Comment by IljaOrlovs** [comment]
The release available via the PyPi is quite old. I will update it eventually, but it will be in a while, as to do that I have to update documentation (at least the rudimentary readme page).

Sadly, I will not have time to do that in the next two weeks.

Please feel free to help me with writing tests/docs. I am bit overwhelmed with other stuff at the moment and simply don't have the capacity to do it.
